### PR TITLE
Merge 1.0 alpha branch

### PR DESCRIPTION
**Pull request by BenSchwab**
1.0-alpha has worked internally for a few months now

Currently it only has support for Observable types -- no Completable, Flowable, Single, etc yet, which I think would be necessary for a solid 1.0 release.

Seems a little premature to call it `1.0.0-alpha` but seems important to bump the major version as this is very much a breaking change.

https://github.com/airbnb/RxGroups/issues/34

@felipecsl @elihart

### CODE REVIEW

**Comment by BenSchwab** [comment]
Some other thoughts before 1.0:

- It might also be nice to add `LifecycleObserver` adapter so RxGroup lifecycle methods don't need to be manually called.

- Also a kotlin extension could probably be used to avoid the code generation via a pattern similar to kotterknife

**Comment by meierjan** [comment]
I'd love to have this published somewhere so we can test it out - maybe event jitpack.

**Comment by meierjan** [comment]
Can you publish it somewhere? It's currently very inconvenient to test. Would be very happy!

**Comment by BenSchwab** [comment]
@meierjan 1.0.0-alpha2 has been uploaded.

Again, this is a pretty rough version of what a full 1.0.0 release would look like, so use with caution.

**Pull request merged**
